In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import time
import random
import math
from datetime import datetime, timedelta

In [3]:
def get_companies(urls_paises = {
    "France": [
        "https://disfold.com/france/companies/?page=1",
        "https://disfold.com/france/companies/?page=2",
        "https://disfold.com/france/companies/?page=3",
        "https://disfold.com/france/companies/?page=4"
    ],
    "Germany": [
        "https://disfold.com/germany/companies/?page=1",
        "https://disfold.com/germany/companies/?page=2",
        "https://disfold.com/germany/companies/?page=3",
        "https://disfold.com/germany/companies/?page=4"
    ],
    "United-Kingdom": [
        "https://disfold.com/united-kingdom/companies/?page=1",
        "https://disfold.com/united-kingdom/companies/?page=2",
        "https://disfold.com/united-kingdom/companies/?page=3",
        "https://disfold.com/united-kingdom/companies/?page=4"
    ],
    "Spain": [
        "https://disfold.com/spain/companies/?page=1",
        "https://disfold.com/spain/companies/?page=2",
        "https://disfold.com/spain/companies/?page=3",
        "https://disfold.com/spain/companies/?page=4"
    ],
    "Italy": [
        "https://disfold.com/italy/companies/?page=1",
        "https://disfold.com/italy/companies/?page=2",
        "https://disfold.com/italy/companies/?page=3",
        "https://disfold.com/italy/companies/?page=4"
    ],
    "Ireland": [
        "https://disfold.com/ireland/companies/?page=1",
        "https://disfold.com/ireland/companies/?page=2"
    ]
} ):
    nombres_empresas = []
    paises_empresas = []

    for pais, urls in urls_paises.items():
        for url in urls:
            response = requests.get(url)
            soup = BeautifulSoup(response.text, 'html.parser')
            table = soup.find('table', {'class': 'striped'})
            rows = table.find_all('tr')

            for row in rows:
                cols = row.find_all('td')
                if len(cols) >= 2:
                    nombres_empresas.append(cols[1].get_text().strip())
                    paises_empresas.append(pais)
            
            time.sleep(1)  # Espera 1 segundo entre solicitudes

    return (nombres_empresas, paises_empresas)

In [4]:
# companies = get_companies()

In [5]:
def comp_name(quantity, countries=None):
    # Si no se especifican países, se utilizan estos por defecto
    if countries is None:
        countries = ["Spain", "Italy", "Germany", "United-Kingdom", "Ireland", "France"]

    # Asumiendo que 'companies' es una tupla (lista_empresas, lista_paises)
    lista_empresas, lista_paises = companies

    # Filtrar las empresas por los países especificados
    empresas_filtradas = [(lista_empresas[i], lista_paises[i]) for i in range(len(lista_empresas)) if lista_paises[i] in countries]

    # Asegurarse de que la cantidad solicitada no sea mayor que la cantidad disponible
    quantity = min(quantity, len(empresas_filtradas))

    # Seleccionar aleatoriamente una cantidad determinada de empresas
    empresas_seleccionadas = random.sample(empresas_filtradas, quantity)

    # Crear y devolver un diccionario con los nombres de las empresas y sus países
    resultado = {nombre: pais for nombre, pais in empresas_seleccionadas}

    return resultado

In [6]:
# comp_name(1058)

In [7]:
name_comp = pd.read_csv('companies.csv', encoding = 'utf-8', delimiter=';')
name_comp.head()
# name_comp['country'].unique()

                             company_name country
0  LVMH Moët Hennessy - Louis Vuitton, SE  France
1                              L'Oréal SA  France
2                Hermès International SCA  France
3                       Christian Dior SE  France
4                        TotalEnergies SE  France

In [8]:
# # Asumiendo que companies es una tupla de dos listas (lista_empresas, lista_paises)
# lista_empresas, lista_paises = companies

# # Crear un DataFrame a partir de la tupla
# df = pd.DataFrame({
#     'company_name': lista_empresas,
#     'country': lista_paises
# })

# # Guardar el DataFrame en un archivo CSV, separado por ';'
# df.to_csv('companies.csv', sep=';', index=False, encoding='utf-8')

In [9]:
cities = {
    "Jerez de la Frontera": "Spain", "Madrid": "Spain", "Barcelona": "Spain",
    "Seville": "Spain", "Valencia": "Spain", "Bilbao": "Spain",
    "Malaga": "Spain", "Zaragoza": "Spain", "Murcia": "Spain", "Palma": "Spain",
    "Paris": "France", "Marseille": "France", "Lyon": "France",
    "Toulouse": "France", "Nice": "France", "Nantes": "France",
    "Strasbourg": "France", "Montpellier": "France", "Bordeaux": "France", "Lille": "France",
    "London": "United Kingdom", "Manchester": "United Kingdom", "Liverpool": "United Kingdom",
    "Edinburgh": "United Kingdom", "Glasgow": "United Kingdom", "Birmingham": "United Kingdom",
    "Leeds": "United Kingdom", "Bristol": "United Kingdom", "Sheffield": "United Kingdom", "Leicester": "United Kingdom",
    "Berlin": "Germany", "Munich": "Germany", "Frankfurt": "Germany",
    "Hamburg": "Germany", "Cologne": "Germany", "Stuttgart": "Germany",
    "Düsseldorf": "Germany", "Dortmund": "Germany", "Essen": "Germany", "Leipzig": "Germany",
    "Rome": "Italy", "Milan": "Italy", "Naples": "Italy",
    "Turin": "Italy", "Palermo": "Italy", "Genoa": "Italy",
    "Bologna": "Italy", "Florence": "Italy", "Bari": "Italy", "Catania": "Italy",
    "Dublin": "Ireland", "Cork": "Ireland", "Limerick": "Ireland",
    "Galway": "Ireland", "Waterford": "Ireland"
}

In [10]:
addresses = {}

# Ciudades en España
spain_cities = [
    "Jerez de la Frontera", "Madrid", "Barcelona", "Seville", "Valencia", "Bilbao",
    "Malaga", "Zaragoza", "Murcia", "Palma"
]

# Ciudades en Francia
france_cities = [
    "Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes",
    "Strasbourg", "Montpellier", "Bordeaux", "Lille"
]

# Ciudades en Reino Unido
uk_cities = [
    "London", "Manchester", "Liverpool", "Edinburgh", "Glasgow", "Birmingham",
    "Leeds", "Bristol", "Sheffield", "Leicester"
]

# Ciudades en Alemania
germany_cities = [
    "Berlin", "Munich", "Frankfurt", "Hamburg", "Cologne", "Stuttgart",
    "Düsseldorf", "Dortmund", "Essen", "Leipzig"
]

# Ciudades en Italia
italy_cities = [
    "Rome", "Milan", "Naples", "Turin", "Palermo", "Genoa",
    "Bologna", "Florence", "Bari", "Catania"
]

# Ciudades en Irlanda
ireland_cities = [
    "Dublin", "Cork", "Limerick", "Galway", "Waterford"
]

# Calles famosas por ciudad
streets_by_city = {
    "Jerez de la Frontera": ["Calle Larga", "Avenida Alcalde Álvaro Domecq", "Calle Sevilla"],
    "Madrid": ["Gran Vía", "Calle Mayor", "Paseo de la Castellana"],
    "Barcelona": ["La Rambla", "Passeig de Gràcia", "Avinguda Diagonal"],
    "Seville": ["Calle Sierpes", "Avenida de la Constitución", "Paseo de Colón"],
    "Valencia": ["Carrer de Colón", "Carrer de Xàtiva", "Carrer de la Pau"],
    "Bilbao": ["Gran Vía", "Calle Licenciado Poza", "Calle Ercilla"],
    "Malaga": ["Calle Marqués de Larios", "Calle Granada", "Calle Alcazabilla"],
    "Zaragoza": ["Paseo de la Independencia", "Calle Don Jaime I", "Calle Alfonso I"],
    "Murcia": ["Gran Vía Escultor Francisco Salzillo", "Avenida Teniente Flomesta", "Calle Trapería"],
    "Palma": ["Passeig des Born", "Carrer de Sant Miquel", "Plaça Major"],
    "Paris": ["Champs-Élysées", "Avenue de l'Opéra", "Rue de Rivoli"],
    "Marseille": ["Rue de la République", "Canebière", "Rue Saint-Ferréol"],
    "Lyon": ["Rue de la République", "Place Bellecour", "Rue Victor Hugo"],
    "Toulouse": ["Place du Capitole", "Allées Jean-Jaurès", "Rue de Metz"],
    "Nice": ["Promenade des Anglais", "Avenue Jean Médecin", "Place Masséna"],
    "Nantes": ["Rue du Calvaire", "Place Royale", "Rue Crébillon"],
    "Strasbourg": ["Place Kléber", "Rue du 22 Novembre", "Rue des Grandes Arcades"],
    "Montpellier": ["Place de la Comédie", "Rue de la Loge", "Rue Saint-Guilhem"],
    "Bordeaux": ["Rue Sainte-Catherine", "Place de la Bourse", "Quai des Chartrons"],
    "Lille": ["Grand'Place", "Rue de la Monnaie", "Rue Esquermoise"],
    "London": ["Oxford Street", "Regent Street", "Baker Street"],
    "Manchester": ["Deansgate", "Market Street", "King Street"],
    "Liverpool": ["Mathew Street", "Bold Street", "Castle Street"],
    "Edinburgh": ["Royal Mile", "Princes Street", "George Street"],
    "Glasgow": ["Buchanan Street", "Argyle Street", "Sauchiehall Street"],
    "Birmingham": ["Bullring", "New Street", "Broad Street"],
    "Leeds": ["Briggate", "Albion Street", "Boar Lane"],
    "Bristol": ["Park Street", "Baldwin Street", "Queen Square"],
    "Sheffield": ["Fargate", "Division Street", "Ecclesall Road"],
    "Leicester": ["High Street", "Granby Street", "Belvoir Street"],
    "Berlin": ["Unter den Linden", "Kurfürstendamm", "Friedrichstraße"],
    "Munich": ["Marienplatz", "Kaufingerstraße", "Maximilianstraße"],
    "Frankfurt": ["Zeil", "Schillerstraße", "Kaiserstraße"],
    "Hamburg": ["Mönckebergstraße", "Jungfernstieg", "Reeperbahn"],
    "Cologne": ["Schildergasse", "Hohe Straße", "Ehrenstraße"],
    "Stuttgart": ["Königstraße", "Calwer Straße", "Wilhelmsplatz"],
    "Düsseldorf": ["Königsallee", "Schadowstraße", "Flinger Straße"],
    "Dortmund": ["Westenhellweg", "Kleppingstraße", "Ostenhellweg"],
    "Essen": ["Kettwiger Straße", "Limbecker Platz", "Rüttenscheider Straße"],
    "Leipzig": ["Grimmaische Straße", "Nikolaistraße", "Karl-Liebknecht-Straße"],
    "Rome": ["Via del Corso", "Via Condotti", "Via Veneto"],
    "Milan": ["Corso Vittorio Emanuele II", "Via Montenapoleone", "Corso Buenos Aires"],
    "Naples": ["Spaccanapoli", "Via Toledo", "Via dei Tribunali"],
    "Turin": ["Via Roma", "Corso San Maurizio", "Via Po"],
    "Palermo": ["Via Vittorio Emanuele", "Corso Vittorio Emanuele", "Via Maqueda"],
    "Genoa": ["Via XX Settembre", "Via Garibaldi", "Via San Lorenzo"],
    "Bologna": ["Via dell'Indipendenza", "Via Ugo Bassi", "Via Rizzoli"],
    "Florence": ["Via de' Tornabuoni", "Piazza della Repubblica", "Via della Vigna Nuova"],
    "Bari": ["Via Sparano", "Corso Cavour", "Corso Vittorio Emanuele II"],
    "Catania": ["Via Etnea", "Via Crociferi", "Via Garibaldi"],
    "Dublin": ["Grafton Street", "O'Connell Street", "Henry Street"],
    "Cork": ["Patrick Street", "Oliver Plunkett Street", "Grand Parade"],
    "Limerick": ["O'Connell Street", "William Street", "Henry Street"],
    "Galway": ["Shop Street", "Eyre Square", "Dominick Street Lower"],
    "Waterford": ["The Quay", "Barronstrand Street", "O'Connell Street"]
}

# Generar direcciones para las ciudades
for city, streets in streets_by_city.items():
    for street in streets:
        for number in range(1, 101):
            address = f"{street}, {number}"
            addresses[address] = city

In [11]:
city_to_province = {
    "Jerez de la Frontera": "Cádiz",
    "Madrid": "Madrid",
    "Barcelona": "Barcelona",
    "Seville": "Seville",
    "Valencia": "Valencia",
    "Bilbao": "Biscay",
    "Malaga": "Malaga",
    "Zaragoza": "Zaragoza",
    "Murcia": "Murcia",
    "Palma": "Balearic Islands",
    "Paris": "Île-de-France",
    "Marseille": "Bouches-du-Rhône",
    "Lyon": "Auvergne-Rhône-Alpes",
    "Toulouse": "Occitanie",
    "Nice": "Provence-Alpes-Côte d'Azur",
    "Nantes": "Loire-Atlantique",
    "Strasbourg": "Bas-Rhin",
    "Montpellier": "Hérault",
    "Bordeaux": "Gironde",
    "Lille": "Nord",
    "London": "Greater London",
    "Manchester": "Greater Manchester",
    "Liverpool": "Merseyside",
    "Edinburgh": "City of Edinburgh",
    "Glasgow": "Glasgow City",
    "Birmingham": "West Midlands",
    "Leeds": "West Yorkshire",
    "Bristol": "Bristol",
    "Sheffield": "South Yorkshire",
    "Leicester": "Leicestershire",
    "Berlin": "Berlin",
    "Munich": "Bavaria",
    "Frankfurt": "Hesse",
    "Hamburg": "Hamburg",
    "Cologne": "North Rhine-Westphalia",
    "Stuttgart": "Baden-Württemberg",
    "Düsseldorf": "North Rhine-Westphalia",
    "Dortmund": "North Rhine-Westphalia",
    "Essen": "North Rhine-Westphalia",
    "Leipzig": "Saxony",
    "Rome": "Lazio",
    "Milan": "Lombardy",
    "Naples": "Campania",
    "Turin": "Piedmont",
    "Palermo": "Sicily",
    "Genoa": "Liguria",
    "Bologna": "Emilia-Romagna",
    "Florence": "Tuscany",
    "Bari": "Apulia",
    "Catania": "Sicily",
    "Dublin": "Dublin",
    "Cork": "Cork",
    "Limerick": "Limerick",
    "Galway": "Galway",
    "Waterford": "Waterford"
}

In [12]:
def remove_short_last_word(input_str):
    words = input_str.split()
    if words:
        last_word = words[-1]
        if len(last_word) <= 3:
            words.pop()
        return ' '.join(words)
    else:
        return input_str

In [13]:
# Función para generar ID de proveedor
def generate_provider_id(company_name, country):
    company_name = remove_short_last_word(company_name)
    # Obtener las iniciales del nombre de la compañía
    words = company_name.split()
    if len(words) >= 3:
        initials = words[0][0] + words[1][0] + words[2][0]
    elif len(words) == 2:
        initials = words[0][:2] + words[1][0]
    elif len(words) == 1:
        initials = words[0][:3]
    else:
        # En caso de que no haya palabras en el nombre
        initials = "XXX"

    # Generar los 3 números aleatorios
    random_digits = ''.join(random.choice('0123456789') for _ in range(3))

    # Mapear el código del país
    country_codes = {
        'Spain': 'SP',
        'France': 'FR',
        'Germany': 'GE',
        'Ireland': 'IR',
        'United Kingdom': 'UK',
        'Italy': 'IT',
    }
    country_code = country_codes.get(country, 'XX')  # 'XX' para países desconocidos

    # Combinar las partes para formar el ID de proveedor
    provider_id = f'prov{initials}{random_digits}{country_code}'

    return provider_id

In [14]:
def assign_location(row):
    country = row['country']
    city = random.choice([c for c, c_country in cities.items() if c_country == country])
    address = random.choice([a for a, a_city in addresses.items() if a_city == city])
    province = city_to_province.get(city, 'Sin Provincia')
    return pd.Series([address, city, province])

In [15]:
df = name_comp.copy()
df['ID_proveedor'] = df.apply(lambda row: generate_provider_id(row['company_name'], row['country']), axis=1)
df['Nombre'] = df['company_name']
df[['Dirección', 'Ciudad', 'Provincia']] = df.apply(assign_location, axis=1)
df = df.drop(['company_name', 'country'], axis=1)
df

,ID_proveedor,Nombre,Dirección,Ciudad,Provincia
0,provLMH042FR,"LVMH Moët Hennessy - Louis Vuitton, SE","Allées Jean-Jaurès, 94",Toulouse,Occitanie
1,provL'O903FR,L'Oréal SA,"Place du Capitole, 49",Toulouse,Occitanie
2,provHeI980FR,Hermès International SCA,"Rue de Rivoli, 14",Paris,Île-de-France
3,provChD941FR,Christian Dior SE,"Avenue Jean Médecin, 90",Nice,Provence-Alpes-Côte d'Azur
4,provTot511FR,TotalEnergies SE,"Canebière, 94",Marseille,Bouches-du-Rhône
...,...,...,...,...,...
1053,provBOI624IR,Bank Of Ireland (Governor & Company Of The),"Shop Street, 21",Galway,Galway
1054,provApp497IR,Applegreen plc,"Eyre Square, 47",Galway,Galway
1055,provMal115IR,Mallinckrodt plc,"Grand Parade, 7",Cork,Cork
1056,provGaG769IR,Gambling.com Group Ltd,"Eyre Square, 90",Galway,Galway
1057,provAbb138IR,Abbey plc,"Dominick Street Lower, 92",Galway,Galway

In [16]:
df.to_csv('proveedores.csv', index=False)
df_prov = df.copy()

# Aquí viene la tabla de pedidos

In [17]:
def generar_id_pedidos(num_elementos):
    lista_id_pedidos = []
    for _ in range(num_elementos):
        pedido = 'pedi' + ''.join(random.choice('0123456789') for _ in range(6))
        lista_id_pedidos.append(pedido)
    return lista_id_pedidos

In [18]:
def check_repetition(lst, target_element):
    threshold = len(lst) * 0.45
    count = 0
    
    for item in lst:
        if item == target_element:
            count += 1
            if count > threshold:
                return True
    
    return False

In [19]:
def selec_prov_aleatorio_v2(num_elementos, df_prov = df_prov):
    # Número de proveedores diferentes
    if num_elementos <= len(df_prov['ID_proveedor']):
        n_prov = int(math.sqrt(num_elementos)) + 1
    else:
        n_prov = num_elementos
    
    # Obtener la lista de ID de proveedores
    id_proveedores = df_prov['ID_proveedor'].tolist()
    
    # Realizar la selección
    lista_seleccionada = random.sample(id_proveedores, n_prov)
    
    # Declaramos la lista prov_selec
    prov_selec = []

    # Calcular la cantidad de repeticiones y añadir los elementos a la lista
    prov_selec.extend(lista_seleccionada)
    while len(prov_selec) < num_elementos:
        sel_random = random.choice(lista_seleccionada)
        if check_repetition(prov_selec, sel_random):
            continue
        n_random = random.randint(1,int(math.sqrt(num_elementos - len(prov_selec))))
        if len(prov_selec) + n_random > num_elementos:          # Esta comrobación es un poco inutil ya que con la raiz cuadrada siempre se va cumplir. 
            continue
        for i in range(n_random):
            prov_selec.append(sel_random)
    
    return prov_selec

In [26]:
def generar_fechas_aleatorias(num_elementos, num_meses = 24):
    # Obtener la fecha actual
    fecha_actual = datetime.now()

    # Calcular la fecha de inicio como 'num_meses' meses atrás
    fecha_inicio = fecha_actual - timedelta(days=num_meses * 30)

    # Generar fechas aleatorias dentro del rango especificado
    fechas_aleatorias = []
    for _ in range(num_elementos):
        # Calcular un número aleatorio de días entre 0 y 'num_meses * 30'
        dias_aleatorios = random.randint(0, num_meses * 30)

        # Calcular la fecha aleatoria dentro del rango
        fecha_aleatoria = fecha_inicio + timedelta(days=dias_aleatorios)

        # Formatear la fecha en "día mes año" y agregarla a la lista
        fecha_formateada = fecha_aleatoria.strftime("%d %m %Y")
        fechas_aleatorias.append(fecha_formateada)

    return fechas_aleatorias

In [128]:
def generar_df_pedidos(num_filas, num_meses = 24):
    numero_filas = 10
    id_ped = generar_id_pedidos(num_filas)
    id_prov = selec_prov_aleatorio_v2(num_filas)
    date = generar_fechas_aleatorias(num_filas, num_meses)

    df_ped = pd.DataFrame({'ID_pedido': id_ped, 'ID_proveedor': id_prov, 'Fecha': date})

    df_ped['Fecha'] = pd.to_datetime(df_ped['Fecha'], format='%d %m %Y')
    df_ped.sort_values('Fecha', inplace=True, ascending= False)
    df_ped = df_ped.reset_index(drop = True)
    df_ped['Fecha'] = df_ped['Fecha'].dt.strftime("%d/%m/%Y")
    return df_ped

In [129]:
df_ped = generar_df_pedidos(10)
df_ped.info()
df_ped

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID_pedido     10 non-null     object
 1   ID_proveedor  10 non-null     object
 2   Fecha         10 non-null     object
dtypes: object(3)
memory usage: 372.0+ bytes

    ID_pedido  ID_proveedor       Fecha
0  pedi542365  provDaA455FR  12/05/2023
1  pedi025497  provBTG217UK  24/01/2023
2  pedi967128  provBAT731UK  22/01/2023
3  pedi779996  provEnM872UK  21/12/2022
4  pedi731125  provEnM872UK  12/12/2022
5  pedi187584  provBTG217UK  05/12/2022
6  pedi101057  provBAT731UK  12/11/2022
7  pedi575987  provBAT731UK  23/08/2022
8  pedi482235  provBTG217UK  09/08/2022
9  pedi042552  provEnM872UK  22/12/2021

In [132]:
def asignar_estados_df(df = df_ped, estados=('Por hacer', 'Pagado', 'De Camino', 'Recibido', 'Almacenado', 'Distribuido')): 
    fechas = pd.to_datetime(df_ped['Fecha'], format='%d/%m/%Y')
    lista_generada = []

    # Obtener el rango de fechas (días) entre la fecha más antigua y la fecha más reciente
    rango_fechas = max(fechas) - min(fechas)

    for _ in range(num_elementos):
        # Calcular la probabilidad basada en la posición relativa de la fecha dentro del rango total
        probabilidad = (max(fechas) - fechas[random.randint(0, len(fechas) - 1)]) / rango_fechas

        # Calcular el índice correspondiente en los valores según la probabilidad relativa
        indice_valor = int(probabilidad * len(valores))

        # Asegurar que el índice no exceda la longitud de la lista de valores
        indice_valor = min(indice_valor, len(valores) - 1)

        lista_generada.append(valores[indice_valor])

    return lista_generada

In [139]:
def asignar_estado(fecha, estados, porcentajes = [0.4, 0.29, 0.15, 0.09, 0.05, 0.02]):
    fecha_actual = datetime.now()
    dias_diferencia = (fecha_actual - fecha).days

    if dias_diferencia <= 0:
        return estados[0]
    elif dias_diferencia > sum(porcentajes):
        return estados[-1]
    else:
        probabilidad_acumulada = 0
        for i, porcentaje in enumerate(porcentajes):
            probabilidad_acumulada += porcentaje
            if dias_diferencia <= probabilidad_acumulada:
                return estados[i]

In [137]:
(10)

['Pagado',
 'Pagado',
 'Recibido',
 'Pagado',
 'Pagado',
 'Por hacer',
 'Recibido',
 'Recibido',
 'Recibido',
 'Recibido']